apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-repo-server
    spec:
      containers:
        - name: repo-server
          image: quay.io/argoproj/argocd:v2.8.13
          # envFrom:
          #   - secretRef:
          #       name: argocd-vault-plugin-credentials